function pres()
{
	presCandid([
	{"candid":"Jejomar Binay", "id":"1", "img":"Images/Binay.jpg"},
	{"candid":"Miriam Defensor-Santiago", "id":"2", "img":"Images/Santiago.jpg"},
	{"candid":"Rodrigo Duterte", "id":"3", "img":"Images/Duterte.jpg"},
	{"candid":"Grace Poe", "id":"4", "img":"Images/Poe.jpg"},
	{"candid":"Manuel Roxas", "id":"5", "img":"Images/Roxas.jpg"}
	])
}

function vice()
{
	viceCandid([
	{"candid":"Alan Peter Cayetano", "id":"6","img":"Images/Cayetano.jpg"},
	{"candid":"Francis Escudero", "id":"7","img":"Images/Escudero.jpg"},
	{"candid":"Gregorio Honasan", "id":"8","img":"Images/Honasan.jpg"},
	{"candid":"Ferdinand R. Marcos", "id":"9","img":"Images/Marcos.jpg"},
	{"candid":"Leonor Robredo", "id":"10","img":"Images/Robredo.jpg"},
	{"candid":"Antonio Trillanes", "id":"11","img":"Images/Trillanes.jpg"}
	])
}

function senate()
{
	senateCandid([
	{"candid":"Sharrif Albani", "id":"12","img":"Images/Albani.jpg"},
	{"candid":"Aldin Ali", "id":"13","img":"Images/Ali.jpg"},
	{"candid":"Raffy Alunan", "id":"14","img":"Images/Alunan.jpg"},
	{"candid":"Ina Ambolodto", "id":"15","img":"Images/Ambolodto.jpg"},
	{"candid":"Godofredo Arquiza", "id":"16","img":"Images/Arquiza.jpg"},
	{"candid":"Levito Baligod", "id":"17","img":"Images/Baligod.jpg"},
	{"candid":"Greco Belgica", "id":"18","img":"Images/Belgica.jpg"},
	{"candid":"Walden Bello", "id":"19","img":"Images/Bello.jpg"},
	{"candid":"Sandra Cam", "id":"20","img":"Images/Cam.jpg"},
	{"candid":"Mel Chavez", "id":"21","img":"Images/Chavez.jpg"},
	{"candid":"Neri Colmenares", "id":"22","img":"Images/Colmenarez.jpg"},
	{"candid":"Leila De Lima", "id":"23","img":"Images/Lima.jpg"},
	{"candid":"Isko Moreno Domagoso", "id":"24","img":"Images/Domagoso.jpg"},
	{"candid":"Ray Dorona", "id":"25","img":"Images/Dorona.jpg"},
	{"candid":"Frank Drilon", "id":"26","img":"Images/Drilon.jpg"},
	{"candid":"Larry Gadon", "id":"27","img":"Images/Gadon.jpg"},
	{"candid":"Win Gatchalian", "id":"28","img":"Images/Gatchalian.jpg"},
	{"candid":"Richard Gordon", "id":"29","img":"Images/Gordon.jpg"},
	{"candid":"TG Guinggona", "id":"30","img":"Images/Guingonna.jpg"},
	{"candid":"Risa Hontiveros", "id":"31","img":"Images/Hontiveros.jpg"},
	{"candid":"Eid Kabalu", "id":"32","img":"Images/Kabalu.jpg"},
	{"candid":"Atty. Lorna Kapunan", "id":"33","img":"Images/Kapunan.jpg"},
	{"candid":"Princess Jacel Kiram", "id":"34","img":"Images/Kiram.jpg"},
	{"candid":"Alma Moreno Lacsamana", "id":"35","img":"Images/Lacsamana.jpg"},
	{"candid":"Panfilo Ping Lacson", "id":"36","img":"Images/Lacson.jpg"},
	{"candid":"Rey Langit", "id":"37","img":"Images/Langit.jpg"},
	{"candid":"Mark Lapid", "id":"38","img":"Images/Lapid.jpg"},
	{"candid":"Dante Liban", "id":"39","img":"Images/Liban.jpg"},
	{"candid":"Romeo Maganto", "id":"40","img":"Images/Maganto.jpg"},
	{"candid":"Edu Manzano", "id":"41","img":"Images/Manzano.jpg"},
	{"candid":"Allan Montano", "id":"42","img":"Images/Montano.jpg"},
	{"candid":"Mon Montaño", "id":"43","img":"Images/Montaño.jpg"},
	{"candid":"Getulio Napeñas", "id":"44","img":"Images/Napenas.jpg"},
	{"candid":"Susan Ople", "id":"45","img":"Images/Ople.jpg"},
	{"candid":"Sergio Osmeña III", "id":"46","img":"Images/Osmena.jpg"},
	{"candid":"Manny Pacquiao", "id":"47","img":"Images/Pacquiao.jpg"},
	{"candid":"Mr. Coop Paez", "id":"48","img":"Images/Paez.jpg"},
	{"candid":"Samuel Pagdilao", "id":"49","img":"Images/Pagdilao.jpg"},
	{"candid":"Jovito Palparan Jr.", "id":"50","img":"Images/Palparan.jpg"},
	{"candid":"Kiko Pangilinan", "id":"51","img":"Images/Pangilinan.jpg"},
	{"candid":"Carlos Jericho Petilla", "id":"52","img":"Images/Petilla.jpg"},
	{"candid":"Ralph Recto", "id":"53","img":"Images/Recto.jpg"},
	{"candid":"Martin Romualdez", "id":"54","img":"Images/Romualdez.jpg"},
	{"candid":"Roman Romulo", "id":"55","img":"Images/Romulo.jpg"},
	{"candid":"Dionisio Santiago", "id":"56","img":"Images/Santiago1.jpg"},
	{"candid":"Vicente Sotto", "id":"57","img":"Images/Sotto.jpg"},
	{"candid":"Francis Tolentino", "id":"58","img":"Images/Tolentino.jpg"},
	{"candid":"Diosdado Valeroso", "id":"59","img":"Images/Valeroso.jpg"},
	{"candid":"Joel Villanueva", "id":"60","img":"Images/Villanueva.jpg"},
	{"candid":"Migz Zubiri", "id":"61","img":"Images/Zubiri.jpg"}
	])
}

function party()
{
	partyCandid([
	{"candid":"1-AALALAY (ISANG ALYANSANG AALALAY SA PINOY SKILLED WORKERS)", "id":"62"},
	{"candid":"1-ABILIDAD (1-ABILIDAD)", "id":"63"},
	{"candid":"1-AHAPO (ONE ADVOCACY FOR HEALTH PROGRESS AND OPPORTUNITY)", "id":"64"},
	{"candid":"1-ANG EDUKASYON (UNA ANG EDUKASYON)", "id":"65"},
	{"candid":"1-CARE (1ST CONSUMERS ALLIANCE FOR RURAL ENERGY, INC.)", "id":"66"},
	{"candid":"1-PABAHAY (ISANG PANGARAP NA BAHAY SA BAGONG BUHAY NG MARALITANG KABABAYAN, INC.)", "id":"67"},
	{"candid":"1-SAGIP (SOCIAL AMELIORATION & GENUINE INTERVENTION ON POVERTY)", "id":"68"},
	{"candid":"1PACMAN (ONE PATRIOTIC COALITION OF MARGINALIZED NATIONALS)", "id":"69"},
	{"candid":"AAB (AKO AN BISAYA)", "id":"70"},
	{"candid":"AAMBIS-OWA (ANG ASOSASYON SANG MANGUNGUMA NGA BISAYA-OWA MANGUNGUMA, INC.)", "id":"71"},
	{"candid":"AANGAT TAYO (AANGAT TAYO)", "id":"72"},
	{"candid":"AASENSO (ATING AGAPAY SENTRONG SAMAHAN NG MGA OBRERO, INC.)", "id":"73"},
	{"candid":"ABAKADA (ABAKADA-GURO)", "id":"74"},
	{"candid":"ABAMIN (ABANTE MINDANAO, INC.)", "id":"75"},
	{"candid":"ABANG LINGKOD (ABANG LINGKOD, INC.)", "id":"76"},
	{"candid":"ABANTE RETIREES (ABANTE RETIREES PARTY-LIST ORGANIZATION)", "id":"77"},
	{"candid":"ABONO (ABONO PARTY-LIST)", "id":"78"},
	{"candid":"ABS (ARTS BUSINESS AND SCIENCE PROFESSIONALS)", "id":"79"},
	{"candid":"ACP (ANAK CENTRAL PARTY)", "id":"80"},
	{"candid":"ACT-CIS (ANTI-CRIME AND TERRORISM COMMUNITY INVOLVEMENT AND SUPPORT, INC.)", "id":"81"},
	{"candid":"ACTS-OFW (ACTS OVERSEAS FILIPINO WORKERS COALITION OF ORGANIZATIONS)", "id":"82"},
	{"candid":"ACT TEACHERS  (ACT TEACHERS PARTY-LIST)", "id":"83"},
	{"candid":"ADDA (ASSOCIATION FOR DEVELOPMENT DEDICATED TO AGRICULTURE AND FISHERIES, INC.)", "id":"84"},
	{"candid":"AGAP (AGRICULTURAL SECTOR ALLIANCE OF THE PHILIPPINES)", "id":"85"},
	{"candid":"AGBIAG! (AGBIAG! TIMPUYOG ILOCANO, INC.)", "id":"86"},
	{"candid":"AGHAM (ALYANSA NG MGA GRUPONG HALIGI NG AGHAM AT TEKNOLOHIYA PARA SA MAMAMAYAN, INC.)", "id":"87"},
	{"candid":"AGRI (AGRI-AGRA NA REPORMA PARA SA MAGSASAKA NG PILIPINAS MOVEMENT)", "id":"88"},
	{"candid":"AI (ABYAN ILONGGO)", "id":"89"},
	{"candid":"AKBAYAN (AKBAYAN CITIZENS' ACTION PARTY)", "id":"90"},
	{"candid":"AKIN (AKBAY KALUSUGAN, INC.)", "id":"91"},
	{"candid":"AKO BICOL (AKO BICOL POLITICAL PARTY)", "id":"92"},
	{"candid":"ALAY BUHAY (ALAY BUHAY COMMUNITY DEVELOPMENT FOUNDATION, INC.)", "id":"93"},
	{"candid":"ALE (ASSOCIATION OF LABORERS AND EMPLOYEES)", "id":"94"},
	{"candid":"ALL-FISH (ALLIANCE OF PHILIPPINE FISHING FEDERATIONS, INC.)", "id":"95"},
	{"candid":"ALONA (ALLIANCE OF ORGANIZATIONS, NETWORKS AND ASSOCIATIONS OF THE PHILIPPINES)", "id":"96"},
	{"candid":"AMA (AAGAPAY SA MATATANDA)", "id":"97"},
	{"candid":"AMEPA OFW (AMEPA OFW ACCESS CENTER, INC.)", "id":"98"},
	{"candid":"AMIN (ANAK MINDANAO PARTY-LIST)", "id":"99"},
	{"candid":"AMOR SEAMAN (ASSOCIATION OF MARINE OFFICER AND RATINGS, INC.)", "id":"100"},
	{"candid":"ANAC-IP (ANG NATIONAL COALITION OF INDIGENOUS PEOPLES ACTION NA)", "id":"101"},
	{"candid":"ANAKALUSUGAN (ALAGAAN NATIN ATING KALUSUGAN)", "id":"102"},
	{"candid":"ANAKPAWIS (ANAKPAWIS", "id":"103"},
	{"candid":"ANG KABUHAYAN (ANG KABUHAYAN)", "id":"104"},
	{"candid":"ANG KASANGGA (KASANGGA SA KAUNLARAN, INC.)", "id":"105"},
	{"candid":"ANGKLA (ANGKLA: ANG PARTIDO NG MGA PILIPINONG MARINO, INC.)", "id":"106"},
	{"candid":"ANG NARS (ANG NARS, INC.)", "id":"107"},
	{"candid":"ANG PROLIFE (ANG PROLIFE)", "id":"108"},
	{"candid":"ANUPA (ALLIANCE FOR NATIONAL URBAN POOR ASSEMBLY, INC.", "id":"109"},
	{"candid":"AN WARAY (AN WARAY)", "id":"110"},
	{"candid":"APPEND (APPEND, INC.)", "id":"111"},
	{"candid":"ASEAN, INC. (ACADEMICIANS, STUDENTS AND EDUCATORS ALLIANCE, INC.)", "id":"112"},
	{"candid":"A TAMBAY (ANG TAO MUNA AT BAYAN)", "id":"113"},
	{"candid":"A TEACHER  (ADVOCACY FOR TEACHER EMPOWERMENT THROUGH ACTION COOPERATION AND HARMONY TOWARDS EDUCATIONAL REFORMS", "id":"114"},
	{"candid":"ATING GURO (ATING GURO)", "id":"115"},
	{"candid":"ATING KOOP (ADHIKAING TINATAGUYOD NG KOOPERATIBA)", "id":"116"},
	{"candid":"AVE (ALLIANCE OF VOLUNTEER EDUCATORS)", "id":"117"},
	{"candid":"AWAKE (AWARENESS OF KEEPERS OF THE ENVIRONMENT, INC.)", "id":"118"},
	{"candid":"AWAT MINDANAO (ANTI-WAR/ANTI-TERROR MINDANAO PEACE MOVEMENT)", "id":"119"},
	{"candid":"BANAT (BARANGAY NATIN)", "id":"120"},
	{"candid":"BAYAN MUNA (BAYAN MUNA)", "id":"121"},
	{"candid":"BH (BAGONG HENERASYON)", "id":"122"},
	{"candid":"BUHAY (BUHAY HAYAAN YUMABONG)", "id":"123"},
	{"candid":"BUTIL (BUTIL FARMERS PARTY)", "id":"124"},
	{"candid":"CANCER (CANCER ALLEVIATION NETWORK ON CARE, EDUCATION AND REHABILITATION, INC.)", "id":"125"},
	{"candid":"CIBAC (CITIZENS' BATTLE AGAINST CORRUPTION)", "id":"126"},
	{"candid":"CLASE (CENTRAL LUZON ALLIANCE FOR SOCIALIZED EDUCATION)", "id":"127"},
	{"candid":"CONSLA (CONFEDERATION OF NON-STOCK SAVINGS AND LOAN ASSOCIATIONS, INC.)", "id":"128"},
	{"candid":"COOP-NATCCO (COOPERATIVE NATCCO NETWORK PARTY)", "id":"129"},
	{"candid":"CWS (CONSTRUCTION WORKERS' SOLIDARITY)", "id":"130"},
	{"candid":"DISABLED/PWD (DISABLED/PILIPINOS WITH DISABILITIES)", "id":"131"},
	{"candid":"DIWA (DEMOCRATIC INDEPENDENT WORKERS ASSOCIATION, INC.)", "id":"132"},
	{"candid":"DUMPER PTDA (DUMPER PHILIPPINES TAXI DRIVERS ASSOCIATION, INC.)", "id":"133"},
	{"candid":"FICTAP (FEDERATION OF INTERNATIONAL CABLE TV AND TELECOMMUNICATIONS ASSOCIATIONS OF THE PHILIPPINES)", "id":"134"},
	{"candid":"GABRIELA (GABRIELA WOMEN'S PARTY)", "id":"135"},
	{"candid":"GLOBAL (GLOBAL WORKERS AND FAMILY FEDERATION, INC.)", "id":"136"},
	{"candid":"GUARDIANS BROTHERHOOD (GUARDIANS REPUBLICAN INTERNATIONAL, INC.)", "id":"137"},
	{"candid":"KABATAAN (KABATAAN PARTY-LIST)", "id":"138"},
	{"candid":"KABAYAN (KABALIKAT NG MAMAMAYAN)", "id":"139"},
	{"candid":"KALINGA (KALINGA-ADVOCACY FOR SOCIAL EMPOWERMENT AND NATION-BUILDING THROUGH EASING POVERTY, INC.)", "id":"140"},
	{"candid":"KAMAIS (KAMAIS PILIPINAS (KAPATIRANG MAGMAMAIS NG PILIPINAS, INC.)", "id":"141"},
	{"candid":"KAP/KAKASA-KA (KAAGAPAY NG NAGKAKAISANG PILIPINONG MAGSASAKA/KABUHAYAN AT KABAHAYAN NG MGA MAGSASAKA)", "id":"142"},
	{"candid":"KGB (KATIPUNAN NG MGA GUARDIANS BROTHERHOOD, INC.)", "id":"143"},
	{"candid":"KMM (KAISAHAN NG MGA MALILIIT NA MAGSASAKA)", "id":"144"},
	{"candid":"KM NGAYON NA (KILOS MAMAMAYAN NGAYON NA)", "id":"145"},
	{"candid":"KUSUG TAUSUG (KUSUG TAUSUG)", "id":"146"},
	{"candid":"LPGMA (LPG MARKETERS ASSOCIATION, INC.)", "id":"147"},
	{"candid":"MAGDALO (MAGDALO PARA SA PILIPINO)", "id":"148"},
	{"candid":"MANILA TEACHERS (MANILA TEACHERS' SAVINGS AND LOAN ASSOCIATION, INC.)", "id":"149"},
	{"candid":"MARINO (MARINO SAMAHAN NG MGA SEAMAN, INC.)", "id":"150"},
	{"candid":"MATA (ANG MATA'Y ALAGAAN)", "id":"151"},
	{"candid":"MELCHORA (MOVEMENT OF WOMEN FOR CHANGE AND REFORM)", "id":"152"},
	{"candid":"METRO (MOVEMENT FOR ECONOMIC TRANSFORMATION AND RIGHTEOUS OPPORTUNITIES)", "id":"153"},
	{"candid":"MIGRANTE (MIGRANTE SECTORAL PARTY OF OVERSEAS FILIPINOS AND THEIR FAMILIES)", "id":"154"},
	{"candid":"MTM PHILS (MAMAMAYAN TUNGO SA MAUNLAD NA PILIPINAS)", "id":"155"},
	{"candid":"NACTODAP (NATIONAL CONFEDERATION OF TRICYCLE OPERATORS AND DRIVERS ASSOCIATION OF THE PHILIPPINES)", "id":"156"},
	{"candid":"OFW FAMILY (OFW FAMILY CLUB, INC.)", "id":"157"},
	{"candid":"PBA (PUWERSA NG BAYANING ATLETA)", "id":"158"},
	{"candid":"PBB (PARTIDO NG BAYAN ANG BIDA)", "id":"159"},
	{"candid":"PISTON (PISTON LAND TRANSPORT COALITION, INC.)", "id":"160"},
	{"candid":"PM (PARTIDO MANGGAGAWA)", "id":"161"},
	{"candid":"RAM (REBOLUSYONARYONG ALYANSANG MAKABANSA)", "id":"162"},
	{"candid":"SAMAKO (SANDIGAN NG MGA MANGGAGAWA SA KONSTRUKSIYON)", "id":"163"},
	{"candid":"SANLAKAS (SANLAKAS)", "id":"164"},
	{"candid":"SBP (SERBISYO SA BAYAN PARTY)", "id":"165"},
	{"candid":"SENIOR CITIZENS (COALITION OF ASSOCIATION OF SENIOR CITIZENS IN THE PHILIPPINES)", "id":"166"},
	{"candid":"SINAG (SINAG TUNGO SA KAUNLARAN)", "id":"167"},
	{"candid":"TAMA (TANGGOL MARALITA)", "id":"168"},
	{"candid":"TGP (TALINO AT GALING PINOY)", "id":"169"},
	{"candid":"TINDERONG PINOY (TINDERONG PINOY PARTY)", "id":"170"},
	{"candid":"TINGOG SINIRANGAN (TINGOG SINIRANGAN (FORMERLY TINGOG LEYTENHON))", "id":"171"},
	{"candid":"TRICAP (TRIBAL COMMUNITIES ASSOCIATION OF THE PHILIPPINES)", "id":"172"},
	{"candid":"TUCP (TRADE UNION CONGRESS PARTY)", "id":"173"},
	{"candid":"UMALAB KA (UGNAYAN NG MARALITA LABAN SA KAHIRAPAN)", "id":"174"},
	{"candid":"UNIDO (UNION OF NATIONALIST DEMOCRATIC FILIPINO ORGANIZATION)", "id":"175"},
	{"candid":"YACAP (YOU AGAINST CORRUPTION AND POVERTY)","id":"176"}      
	])
}